### PR TITLE
support laravel 8

### PR DESCRIPTION
**Pull request by stephanus-stuff**

### CODE REVIEW

**Comment by ziming** [comment]
Hi @asantibanez 

It is recently mentioned by Dries Vint on twitter (Oct 2nd) that bug fixing support for Laravel 7 will end on next Tuesday.

Hence, it would be really great if this PR is good to merge so everyone who uses your package can upgrade to laravel 8. Thank you! :)

**Comment by asantibanez** [comment]
Hi @stephanus-stuff @ziming 

Thanks for you interest on the package. Doing a run through of all Livewire components released and tagging them to support L8 and Livewire v2. Hopefully will have them ready this week.

**Comment by chrisdicarlo** [comment]
Is this coming soon?  Can't use the package otherwise :)

**Comment by ziming** [comment]
Thank you @asantibanez , I look forward to it

**Pull request closed without merging**
